name: CI/CD - Frontend & Backend (DockerHub + GHCR)

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOCKERHUB_NAMESPACE: ${{ secrets.DOCKER_USERNAME }}
  GHCR_NAMESPACE: ${{ github.repository_owner }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    ##################################################
    # 🔁 1. Checkout the repository
    ##################################################
    - name: Checkout code
      uses: actions/checkout@v3

    ##################################################
    # ⚙️ 2. Set up Python (for backend testing)
    ##################################################
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    ##################################################
    # 🧪 3. Install backend deps, run tests & lint
    ##################################################
    - name: Install dependencies & run tests (User Service)
      working-directory: ./user-service
      run: |
        pip install -r requirements.txt
        pip install pytest flake8
        PYTHONPATH=. pytest || true
        flake8 app.py || true

    ##################################################
    # 🐳 4. Build Docker Images
    ##################################################
    - name: Build backend Docker image
      run: |
        docker build -t $DOCKERHUB_NAMESPACE/image-uploader-backend:latest \
                     -t ghcr.io/$GHCR_NAMESPACE/image-uploader-backend:latest \
                     ./user-service

    - name: Build frontend Docker image
      run: |
        docker build -t $DOCKERHUB_NAMESPACE/image-uploader-frontend:latest \
                     -t ghcr.io/$GHCR_NAMESPACE/image-uploader-frontend:latest \
                     ./frontend

    ##################################################
    # 🔐 5. Log in to DockerHub
    ##################################################
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    ##################################################
    # 📤 6. Push images to DockerHub
    ##################################################
    - name: Push backend to DockerHub
      run: docker push $DOCKERHUB_NAMESPACE/image-uploader-backend:latest

    - name: Push frontend to DockerHub
      run: docker push $DOCKERHUB_NAMESPACE/image-uploader-frontend:latest

    ##################################################
    # 🔐 7. Log in to GHCR
    ##################################################
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    ##################################################
    # 📤 8. Push images to GHCR
    ##################################################
    - name: Push backend to GHCR
      run: docker push ghcr.io/$GHCR_NAMESPACE/image-uploader-backend:latest

    - name: Push frontend to GHCR
      run: docker push ghcr.io/$GHCR_NAMESPACE/image-uploader-frontend:latest
