name: CI/CD - Booking App (DockerHub + GHCR)

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOCKERHUB_NAMESPACE: ${{ secrets.DOCKER_USERNAME }}
  GHCR_NAMESPACE: ${{ github.repository_owner }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    ##################################################
    # 🔁 1. Checkout the repository
    ##################################################
    - name: Checkout code
      uses: actions/checkout@v3

    ##################################################
    # ⚙️ 2. Set up Python (for backend testing)
    ##################################################
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    ##################################################
    # 🧪 3. Install deps, run tests & lint (User Service)
    ##################################################
    - name: Install dependencies & run tests (User Service)
      working-directory: ./user-service
      run: |
        pip install -r requirements.txt
        pip install pytest flake8
        PYTHONPATH=. pytest
        flake8 app.py

    ##################################################
    # 🐳 4. Build Docker Images
    ##################################################
    - name: Build User Service image
      run: |
        docker build -t $DOCKERHUB_NAMESPACE/booking-user:latest \
                     -t ghcr.io/$GHCR_NAMESPACE/booking-user:latest \
                     ./user-service

    - name: Build Flight Service image
      run: |
        docker build -t $DOCKERHUB_NAMESPACE/booking-flight:latest \
                     -t ghcr.io/$GHCR_NAMESPACE/booking-flight:latest \
                     ./flight-service

    - name: Build Frontend image
      run: |
        docker build -t $DOCKERHUB_NAMESPACE/booking-frontend:latest \
                     -t ghcr.io/$GHCR_NAMESPACE/booking-frontend:latest \
                     ./frontend

    ##################################################
    # 🔐 5. Login to DockerHub
    ##################################################
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    ##################################################
    # 📤 6. Push images to DockerHub
    ##################################################
    - name: Push images to DockerHub
      run: |
        docker push $DOCKERHUB_NAMESPACE/booking-user:latest
        docker push $DOCKERHUB_NAMESPACE/booking-flight:latest
        docker push $DOCKERHUB_NAMESPACE/booking-frontend:latest

    ##################################################
    # 🔐 7. Login to GHCR
    ##################################################
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GH_PAT }}

    ##################################################
    # 📤 8. Push images to GHCR
    ##################################################
    - name: Push images to GHCR
      run: |
        docker push ghcr.io/$GHCR_NAMESPACE/booking-user:latest
        docker push ghcr.io/$GHCR_NAMESPACE/booking-flight:latest
        docker push ghcr.io/$GHCR_NAMESPACE/booking-frontend:latest
