name: Booking App CI/CD (Multi-Registry)

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOCKERHUB_NAMESPACE: ${{ secrets.DOCKER_USERNAME }}
  GHCR_NAMESPACE: ${{ secrets.GHCR_USERNAME || github.repository_owner }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    ### 1. CHECKOUT ###
    - uses: actions/checkout@v4

    ### 2. SETUP BUILDX ###
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    ### 3. BUILD IMAGES ###
    - name: Build User Service
      working-directory: ./user-service
      run: |
        docker build -t user-service:latest \
                    -t $DOCKERHUB_NAMESPACE/booking-user:latest \
                    -t ghcr.io/$GHCR_NAMESPACE/booking-user:latest .

    - name: Build Flight Service
      working-directory: ./flight-service
      run: |
        docker build -t flight-service:latest \
                    -t $DOCKERHUB_NAMESPACE/booking-flight:latest \
                    -t ghcr.io/$GHCR_NAMESPACE/booking-flight:latest .

    - name: Build Frontend
      working-directory: ./frontend
      run: |
        docker build -t frontend:latest \
                    -t $DOCKERHUB_NAMESPACE/booking-frontend:latest \
                    -t ghcr.io/$GHCR_NAMESPACE/booking-frontend:latest .

    ### 4. LOGIN TO REGISTRIES ###
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME || github.actor }}
        password: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}

    ### 5. PUSH IMAGES ###
    - name: Push to DockerHub
      run: |
        docker push $DOCKERHUB_NAMESPACE/booking-user:latest
        docker push $DOCKERHUB_NAMESPACE/booking-flight:latest
        docker push $DOCKERHUB_NAMESPACE/booking-frontend:latest

    - name: Push to GHCR
      run: |
        docker push ghcr.io/$GHCR_NAMESPACE/booking-user:latest
        docker push ghcr.io/$GHCR_NAMESPACE/booking-flight:latest
        docker push ghcr.io/$GHCR_NAMESPACE/booking-frontend:latest

    ### 6. KUBERNETES DEPLOYMENT ###
    - name: Deploy to Cluster
      if: ${{ secrets.KUBE_CONFIG }}
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
        export KUBECONFIG=kubeconfig
        
        # Update images
        kubectl set image -n booking-app deployment/user-service \
          user-service=ghcr.io/$GHCR_NAMESPACE/booking-user:latest
        
        kubectl set image -n booking-app deployment/flight-service \
          flight-service=ghcr.io/$GHCR_NAMESPACE/booking-flight:latest
        
        kubectl rollout restart -n booking-app deployment/frontend